### ISSUE TITLE
auto width owl-items problem

### ISSUE THREAD

**Issue by Luarb** [vitalii-andriiovskyi/ngx-owl-carousel-o#13]
Hi again.
Is it possible to have auto-width owl items 
and the stage container to be the total of the widths ?

I tried to apply css on stage  `display:flex-inline ` and owl-items` width:auto ` 
but the sliding does not move with the owl items size, it leaves an empty space 
on the end of carousel, which I think is the sum of the items width subtracting 
the stage width.

I am trying to put as much details as possible, but the idea is that the owl items
to have an auto width depending on their content, not the same width [ stage/number of owl items].

**Comment by vitalii-andriiovskyi** [comment]
Hi.
The stage container takes the width which is the sum of all slides' width. The empty space at the end of the carousel appears because of the strategy of scrolling (moving) slides. When you press the `next` button carousel scrolls on one slide. So the new slide appears beside left border of the carousel. 

When scrolling reaches the end of the carousel, it's needed to show the last slide keeping the stragegy. 
So scrolling by slides makes that empty space. For now code can't avoid this behavior. 

As a workaround you can turn on the option `loop`. In this case the empty space will be filled by part of first slide. 

Slides can have different width. But it's needed to set the width of every slide through `@Input` `width` manually. The code doesn't calculate the width of the content of the slide. Example is [here](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/blob/develop/apps/demo-owl-carousel/src/app/home/home.component.ts)

**Comment by Luarb** [comment]
I guess I am going to use the string length to calculate the width of each owl,
than apply the width option on the slides. Thank you for your support.
