### ISSUE TITLE
Change style of the owl-dots

### ISSUE THREAD

**Issue by monikap90** [vitalii-andriiovskyi/ngx-owl-carousel-o#262]
Hello,
I want to change the color and the width of the dots in the owl-carousel. I have tried everything and I really do not know what to do anymore. Please can somebody help me.

.owl-theme .owl-dots .owl-dot span {
    background: pink !important;
    width: 40px !important;
  }
  
  .owl-theme .owl-dots .owl-dot.active span,
  .owl-theme .owl-dots .owl-dot:hover span {
    background: red !important;
  }

**Comment by vitalii-andriiovskyi** [comment]
@monikap90 

Probably you don't get the result because of Angular encapsulation.

I you're adding this CSS to component styles, put `::ng-deep` before `.owl-theme .owl-dots .owl-dot span` - `::ng-deep .owl-theme .owl-dots .owl-dot span`.

or add you CSS to the main `style.scss` file. However in this case wrap carousel in a `<div class="customClass">` and use `customClass` in your CSS
