### ISSUE TITLE
Infinite loop with two carousels

### ISSUE THREAD

**Issue by DenisRakhuba** [vitalii-andriiovskyi/ngx-owl-carousel-o#30]
Hi, I'm trying to implement two connected between each other sliders with infinite loop, but when I get to the last item and trying to select next - it rewind me back to the first, instead of moving forward.
Is there a way to handle this somehow? Maybe this problem appears in my case since I'm using click event with owl.to(index) when selecting slide?

Here's view example:
```
<owl-carousel-o [options]="categoriesOptions" #owlCat>
    <ng-container *ngFor="let category of categories.items; let i = index" >
      <ng-template carouselSlide [id]="category.id">
      <div class="category">
        <span (click)="slideTo(category.id)" class="category__title">{{category.displayedName}}</span>
      </div>
      </ng-template>
    </ng-container>
  </owl-carousel-o>

<owl-carousel-o [options]="carouselOptions" #owlMac  (changed)="changeSlide($event)">
    <ng-container *ngFor="let category of categories.items; let i = index" >
      <ng-template carouselSlide [id]="category.id">
        <div class="machine" *ngFor="let machine of machines; let index = index"
        [class.animated-cell]="index == animatedIndex"
        > </div>
      </ng-template>
    </ng-container>
  </owl-carousel-o>
```

And controller:
```
categoriesOptions: any = {
    loop: true,
    mouseDrag: false,
    touchDrag: false,
    pullDrag: false,
    center: true,
    margin: 10,
    responsive: {
      0: {
        items: 4,
        loop: true,
      },
      400: {
        items: 4,
        loop: true,
      },
      740: {
        items: 4,
        loop: true,
      },
      940: {
        items: 4,
        loop: true,
      }
    }
  };

  carouselOptions: any = {
    loop: true,
    mouseDrag: true,
    touchDrag: true,
    pullDrag: true,
    responsive: {
      0: {
        items: 1,
        loop: true,
      },
      400: {
        items: 1,
        loop: true,
      },
      740: {
        items: 1,
        loop: true,
      },
      940: {
        items: 1,
        loop: true,
      }
    }
  };
```
```

 slideTo(category: string) {
    this.owlMac.to(category);
  }

  changeSlide($event) {
    if (this.owlCat) {
      this.category$.next($event.slides[0].id);
      this.owlCat.to($event.slides[0].id)
    } 
  }
```

Thanks

**Comment by vitalii-andriiovskyi** [comment]
Hi @DenisRakhuba.
Sorry for the late answer. 

You can't loop two carousels using `.to()` method. This is because in order to organize the loop for single carousel the code created cloned slides which get the id `cloned-slide-1`, `cloned-slide-2` and so on. 

![image](https://user-images.githubusercontent.com/23376582/57245124-c2364600-7042-11e9-8811-22ca595befb5.png)


But lib doesn't expose such ids when any of events fires. It removes `cloned-` prefix and exposes `slide-1`. So you  sometimes you can see `slide-5`, `slide-1`, `slide-2` instead of  `cloned-slide-5`, `slide-1`, `slide-2`.

You can solve the problem partly by enabling and hiding the dots for the second carousel using css and using the method `moveByDot(dot-id: string)`  (`owlMac.moveByDot(dot-id: string)` to your case). Dots have own data structure which is in property `dotsData`. In your case `owlMac.dotsData`. Example of data structure:

![image](https://user-images.githubusercontent.com/23376582/57245709-29a0c580-7044-11e9-8e6b-d461958b3f91.png)

so for your specific case you can use the code:
```html
<owl-carousel-o [options]="categoriesOptions" #owlCat>
    <ng-container *ngFor="let category of categories.items; let i = index" >
      <ng-template carouselSlide [id]="category.id">
      <div class="category">
        <span (click)="owlMac.moveByDot(owlMac.dotsData.dots[i].id)" class="category__title">{{category.displayedName}}</span>
      </div>
      </ng-template>
    </ng-container>
  </owl-carousel-o>
```
__Note__: the `moveByDot()` is the part of logic implemented in dots. This logic has own optimisation of scrolling the carousel to the needed slide. E.g. If you see the last slide and want to see the first one, the lib will show the first one using loop. If you see the second slide of all the slides and want to see the last one, the lib could scroll the carousel to the left-hand side showing the slide preceding the first one. 

I didn't mention the method  `moveByDot()` in the docs because it's needed very rare and uses dots ids which are generated automatically and can't be changed by the developer. These ids could be the same for different carousels but they are scoped to the specific carousel. So pay attention to what carousel the dots ids belong to. 

To see dots ids in your case use `@ViewChild() owlCat` in your component.

Hope it'll help you.

**Comment by DenisRakhuba** [comment]
Hi, thanks a lot for your reply.
I've tried to switch to navigation through dots, but still have same issue with rewinding back after last element.
First carousel in my case is just a line with titles for categories. And above it there's second carousel with items from those categories. Titles are allowed only to switch by click, while items are draggable. 
So I need to update them both depending whether it was clicked or dragged.
Here's how it looks:
<a href="http://piccy.info/view3/13156494/8738f41ab6d036baa1c00e34a75c04a0/" target="_blank"><img src="http://i.piccy.info/i9/35ac42b9cbd41125e831837e2675a790/1557215355/5514/1316731/Screen_Shot_2019_05_07_at_10_39_18_AM_240.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2019-05-07-07-49/i9-13156494/156x240-r" target="_blank"><img src="http://i.piccy.info/a3/2019-05-07-07-49/i9-13156494/156x240-r/i.gif" alt="" border="0" /></a>

I updated the code with enabling dots on both carousel to be able navigate from any of them, but it still rewinds back as I said.
```
<owl-carousel-o [options]="categoriesOptions" #owlCat>
    <ng-container *ngFor="let category of categories.items; let i = index" >
      <ng-template carouselSlide [id]="category.id">
      <div class="category">
        <span (click)="slideTo(owlMac.dotsData.dots[i].id)" class="category__title">{{category.displayedName}}</span>
      </div>
      </ng-template>
    </ng-container>
  </owl-carousel-o>

<owl-carousel-o [options]="carouselOptions" #owlMac  (changed)="changeSlide($event)">
    <ng-container *ngFor="let category of categories.items; let i = index" >
      <ng-template carouselSlide [id]="category.id">
        <div class="machine" *ngFor="let machine of machines; let index = index"
        [class.animated-cell]="index == animatedIndex"
        > </div>
      </ng-template>
    </ng-container>
  </owl-carousel-o>
```
```
slideTo(category: string) {
    this.owlMac.moveByDot(category)
  }

  changeSlide($event) {
    if (this.owlCat) {
      this.category$.next($event.slides[0].id);
      this.owlCat.moveByDot(this.owlCat.dotsData.dots[$event.startPosition].id)
    } 
  }
```

**Comment by vitalii-andriiovskyi** [comment]
Hi @DenisRakhuba.

There was a internal issue. I solved it and publish a new version of `ngx-owl-carousel-o`. It's `v1.1.3`. Please, install it. Your current implementation should remain the same. Hope your case will work well now. At least my reproduction of your case is working.

**Comment by DenisRakhuba** [comment]
Wow, thanks a lot. Now it works perfectly. Thank again.
