### ISSUE TITLE
Update to Angular 8

### ISSUE THREAD

**Issue by danieldanielecki** [vitalii-andriiovskyi/ngx-owl-carousel-o#37]
As in the title.

**Comment by vitalii-andriiovskyi** [comment]
Hi @danieldanielecki.

Updated. Please, install `v2.0.0`.

**Comment by danieldanielecki** [comment]
@vitalii-andriiovskyi the new version breaks when uploading to Firebase Cloud Functions with the following errors. Had to roll back into `1.1.5` again in order to use your plugin.

```
Error: Error occurred while parsing your function triggers.

ReferenceError: Event is not defined
    at C:\users\ddanielecki\OneDrive\Desktop\thesisapp\node_modules\ngx-owl-carousel-o\bundles\ngx-owl-carousel-o.umd.js:2987:46
    at C:\users\ddanielecki\OneDrive\Desktop\thesisapp\node_modules\ngx-owl-carousel-o\bundles\ngx-owl-carousel-o.umd.js:3018:6
    at C:\users\ddanielecki\OneDrive\Desktop\thesisapp\node_modules\ngx-owl-carousel-o\bundles\ngx-owl-carousel-o.umd.js:2:68
    at Object.<anonymous> (C:\users\ddanielecki\OneDrive\Desktop\thesisapp\node_modules\ngx-owl-carousel-o\bundles\ngx-owl-carousel-o.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

**Comment by vitalii-andriiovskyi** [comment]
@danieldanielecki 
The problem is with `@Hostlistener`.

The original code of the library has: 
```typescript
@HostListener('document:visibilitychange', ['$event'])
  onVisibilityChange(ev: Event) {        // <-----    typings of the argument `ev`
     // needed code
  };
```

After bundling we get this:
```javascript
__decorate([
            core.HostListener('document:visibilitychange', ['$event']),
            __metadata("design:type", Function),
            __metadata("design:paramtypes", [Event]),  // <-----   the object `Event` is added here and it causes the error. 
            __metadata("design:returntype", void 0)
        ], CarouselComponent.prototype, "onVisibilityChange", null);
```

This code is different from the one compiled by Angular 7. 

So this problem emerges due to changes in Angular 8. 

I faced the problem `ReferenceError: Event is not defined` in the case of using Angular Universal. This issue is described in docs for `ngx-owl-carousel-o`: [Issue with Angular Universal and Solution](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#issue-with-angular-universal-and-solution)

Maybe there is a way to use this solution in your case. 

Also it's possible to change `onVisibilityChange(ev: Event) {`  into `onVisibilityChange(ev: any) {`. But this not a good solution.

**Comment by danieldanielecki** [comment]
@vitalii-andriiovskyi thanks for the info. I'm using Angular Universal for SSR and I guess it's also the case. My server to render this is in NestJS though, but based on this comment I think it should be quite doable to make.
