### ISSUE TITLE
If data item has only one, it will always show " option 'items' in your options is bigger than number of slides; "

### ISSUE THREAD

**Issue by rainstormza** [vitalii-andriiovskyi/ngx-owl-carousel-o#6]
![image](https://user-images.githubusercontent.com/4003032/48999326-df5c1400-f188-11e8-9c65-aea00ff6fb01.png)

I always receive log like this when my carouselData has the only item.

```
  carouselData: CarouselData[] = [
    { id: 'slide-1', text: 'Slide 1 HM', dataMerge: 2, width: 300, dotContent: 'text1'}
  ];
```

**Comment by vitalii-andriiovskyi** [comment]
You see this notification in the case when the option `items` is bigger than the total number of sliders. 
E.g., you set `items` to 2 (`items=2`) and the total number of slides is just 1. This means you ant to show 2 slides in carousel. But it's impossible because there's just one slide. This notification warns you about this situation.

**Comment by rainstormza** [comment]
```
carouselData: CarouselData[] = [
    { id: 'slide-1', text: 'Slide 1 HM', dataMerge: 2, width: 300, dotContent: 'text1'}
  ];
```

```
customOptions: any = {
    // items: '1',
  }

```

Actually, I set ```items=1``` and array data has only one but the warning still show.

It happens when option items equal array data. 
eg. items: 1, data: 1 (length)
items:2, data: 2 (length)
items:3, data: 3 (length)

I tried your demo it shows warning too.

**Comment by vitalii-andriiovskyi** [comment]
This is because of the internal checking (`if (items >= this._items.length) {...`,
where `items` is the option `items` and `this._items.length` is the number of all slides. 
The intention of this is to set the most correct value of items and to notify the developer of it. Also, in this case, the navigation gets disabled. There's no sense to use the navigation in this occasion and the developer should know why the navigation got disabled (disappeared). 

I agree, my notification `option \'items\' in your options is bigger than number of slides; This option is updated to current number of slides and navigation got disabled` is confusing in your situation. I'll make the change. So, when the option `items` will be equal to the length of array data, this words `option \'items\' in your options is bigger than number of slides; This option is updated to current number of slides and` won't be logged. 

However, the notification about disabling the navigation will remain.

**Comment by rainstormza** [comment]
I argee with you that the notification of disabling navigation will remain.

Anyway, Does this notification still show when I build on production mode(ng build --prod)?

**Comment by vitalii-andriiovskyi** [comment]
Yes, this notification will be remained in production version yet. 
You can remove it writing in `main.ts`:
```typescript
if (environment.production) {
    enableProdMode();
    if(window){
     window.console.log=function(){};
     window.console.warn=function(){};
    }
}
```

However, this will skip all notifications written in `console.log()`.

**Comment by rainstormza** [comment]
I understand that we can override console function but I think that is not a practical way.

I think any logging shouldn't be in production mode.
Is it possible that only show logging in development mode within the library?

**Comment by vitalii-andriiovskyi** [comment]
For now it's not possible. 

Anyway, it'll be needed to pass  environment into library for disabling logging in production mode. When `enviroment.production` is `true`, logging will be disabled. Realizing this feature will take some time.

**Comment by vitalii-andriiovskyi** [comment]
New 2 versions `v0.1.1` for __*Angular 6*__ and  `v1.0.2` for __*Angular 7*__ disable logging on production automatically.
