### ISSUE TITLE
Responsive option doesn't work with dynamic content

### ISSUE THREAD

**Issue by kdzik** [vitalii-andriiovskyi/ngx-owl-carousel-o#61]
When I try to put dynamic data into the carousel it stops being responsive. The carousel changes it's number of items only when I refresh a page on specific width. Here's my code:

HTML
`  
<owl-carousel-o [options]="customOptions">
      <ng-container *ngFor="let slide of productsOnDiscount$ | async"> 
   
        <ng-template carouselSlide>
          <div class="slide">
            <img src="http://localhost:8080/images/{{slide.image[0].photoName}}">
  
            <span class="price">{{slide.productPrice | currency:'':'':'1.2-2'}}</span>
          </div>
          <h4>{{slide.productName}}</h4>
          <h5>{{slide.productDiscount}}</h5>
        </ng-template>
      </ng-container>

    </owl-carousel-o> `

OwlOptions
`
  customOptions: OwlOptions = {
    loop: true,
    mouseDrag: true,
    touchDrag: true,
    pullDrag: true,
    dots: true,
    navSpeed: 700,
    responsive: {
      0: {
        items: 1
      },
      400: {
        items: 2
      },
      740: {
        items: 3
      },
      940: {
        items: 4
      }
    },
    nav: false,
    autoplay: true,
    autoplayTimeout: 3500,
    smartSpeed: 1500
  }`

**Comment by vitalii-andriiovskyi** [comment]
Hi @kdzik 

The carousel should change the number of slides/items every time the ` productsOnDiscount$` gets new data. When the carousel gets rerendered, the first slide correspondes to the data from the first item of your array (or Map or Set). This behavior is implemented because the carousel don't know the order of your new data. That is whether new slides are added to the end or inserted in the middle of the array. 

To show the same active slide affter getting new data you can find the position of that slide in your new data and set it using the option `startPosition`.

**Comment by amarbisht09** [comment]
First, you must get the image URL along with your slide object, and then you can use it like :

` <owl-carousel-o [options]="customOptions">
        <ng-container *ngFor="let item of productsOnDiscount$ | async"">
         <ng-template carouselSlide carouselSlide [id]="item.productName">
      <div class="slide">
        <img src="{{slide.image[0].photoName}}">
        <span class="price">{{slide.productPrice | currency:'':'':'1.2-2'}}</span>
      </div>
      <h4>{{slide.productName}}</h4>
      <h5>{{slide.productDiscount}}</h5>
    </ng-template>
        </ng-container>
</owl-carousel-o>`

It's mandatory to use **[Id]** attribute with the **string** typed value, otherwise, carousal will get disappeared.
